import type { Metadata } from "next";
import TopBar from "../components/TopBar";
import Navbar from "@/components/Navbar";
import { Inter } from "next/font/google";
import PalmierLandingPageFooter from "@/components/PalmierLandingPageFooter";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <>
        <TopBar/>
        <Navbar/>
        {children}
        </>
        <PalmierLandingPageFooter/>
        </body>
    </html>
  );
}
